# Generated by Django 3.0.5 on 2020-05-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='型号')),
                ('color', models.CharField(blank=True, max_length=5, null=True, verbose_name='颜色')),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='品牌')),
            ],
            options={
                'verbose_name': '硒鼓',
                'verbose_name_plural': '硒鼓',
                'db_table': 'cartridge',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depname', models.CharField(blank=True, db_column='depName', max_length=20, null=True, verbose_name='名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=50, verbose_name='品牌和型号')),
                ('brand', models.CharField(blank=True, editable=False, max_length=10, null=True, verbose_name='品牌')),
                ('pic', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='图片')),
                ('sn', models.CharField(blank=True, max_length=50, null=True, verbose_name='序列号')),
                ('room', models.CharField(blank=True, max_length=20, null=True, verbose_name='房间号')),
                ('buytime', models.DateField(blank=True, db_column='buyTime', null=True, verbose_name='购置时间')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('recordtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('depid', models.ForeignKey(db_column='depID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.department', verbose_name='责任处室')),
            ],
            options={
                'verbose_name': '设备管理',
                'verbose_name_plural': '设备',
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ecsstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名称')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
                'db_table': 'ecsstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dingID', models.CharField(blank=True, max_length=20, null=True, verbose_name='钉钉编号')),
                ('name', models.CharField(db_column='memberName', max_length=10, verbose_name='姓名')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('depid', models.ForeignKey(blank=True, db_column='depID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.department', verbose_name='所属处室')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('brand', models.CharField(blank=True, max_length=10, null=True, verbose_name='品牌')),
                ('pic', models.CharField(blank=True, max_length=100, null=True)),
                ('cartridges', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用的硒鼓')),
            ],
            options={
                'verbose_name': '打印机型号',
                'verbose_name_plural': '型号',
                'db_table': 'printer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='sys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(blank=True, db_column='codeName', max_length=20, null=True, verbose_name='名称')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='排序')),
                ('type', models.IntegerField(blank=True, choices=[(1, '设备类别'), (2, '设备状态'), (3, '设备审批'), (4, '借用状态')], null=True, verbose_name='代码类别')),
            ],
            options={
                'verbose_name': '代码',
                'verbose_name_plural': '代码',
                'db_table': 'sys',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecordBorrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etime', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('stime', models.DateField(blank=True, null=True, verbose_name='借用时间')),
                ('reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='借用原因')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('recordtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('depid', models.ForeignKey(db_column='depID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.department', verbose_name='借用处室')),
                ('devices', models.ManyToManyField(to='htgl.Device', verbose_name='借用设备')),
                ('status', models.ForeignKey(blank=True, db_column='status', limit_choices_to={'type': '3'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyzt', to='htgl.sys', verbose_name='状态')),
                ('userid', models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.member', verbose_name='借用人')),
            ],
            options={
                'verbose_name': '设备借用',
                'verbose_name_plural': '设备借用',
                'db_table': 'record_borrow',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RecordApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(blank=True, max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True, verbose_name='申领人')),
                ('deptid', models.CharField(blank=True, db_column='deptID', max_length=20, null=True)),
                ('department', models.CharField(blank=True, max_length=20, null=True, verbose_name='申领部门')),
                ('recordtime', models.DateTimeField(blank=True, null=True, verbose_name='申领时间')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='数量')),
                ('ctime', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('crid', models.ForeignKey(db_column='crID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.Cartridge', verbose_name='申领耗材')),
            ],
            options={
                'verbose_name': '耗材申领记录',
                'verbose_name_plural': '耗材申领记录',
                'db_table': 'record_apply',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PrinterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('brand', models.CharField(blank=True, max_length=10, null=True, verbose_name='品牌')),
                ('pic', models.CharField(blank=True, max_length=100, null=True)),
                ('cartridges', models.ManyToManyField(to='htgl.Cartridge', verbose_name='使用的硒鼓')),
            ],
            options={
                'verbose_name': '打印机型号',
                'verbose_name_plural': '型号',
                'db_table': 'printertype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='内网IP')),
                ('internetip', models.CharField(blank=True, max_length=15, null=True, verbose_name='互联网ip')),
                ('os', models.CharField(default='Windows Server 2008 R2', max_length=50, verbose_name='操作系统')),
                ('sn', models.CharField(max_length=50, unique=True, verbose_name='实例id')),
                ('net', models.CharField(choices=[('VPN1', 'VPN1'), ('VPN2', 'VPN2'), ('VPN3', 'VPN3')], default='VPN1', max_length=4)),
                ('group', models.IntegerField(choices=[(1, '转塘集群'), (2, '青山湖集群')], default=1)),
                ('cpu', models.CharField(blank=True, default='8核', max_length=20, null=True, verbose_name='CPU')),
                ('ram', models.CharField(blank=True, default='16G', max_length=20, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, default='500G', max_length=20, null=True, verbose_name='硬盘')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('recordtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('sort', models.IntegerField(default=99)),
                ('status', models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.PROTECT, to='htgl.ecsstatus', verbose_name='状态')),
            ],
            options={
                'verbose_name': '云服务器',
                'verbose_name_plural': '云服务器',
                'db_table': 'ecs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='memid',
            field=models.ForeignKey(db_column='memID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.member', verbose_name='责任人'),
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', limit_choices_to={'type': '2'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='zt', to='htgl.sys', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(db_column='type', limit_choices_to={'type': '1'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.sys', verbose_name='类别'),
        ),
        migrations.CreateModel(
            name='RecordDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returntime', models.DateField(blank=True, null=True, verbose_name='归还时间')),
                ('recordtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('borrowid', models.ForeignKey(db_column='borrowID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.RecordBorrow', verbose_name='借用id')),
                ('did', models.ForeignKey(db_column='dID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.Device', verbose_name='设备id')),
                ('status', models.ForeignKey(blank=True, db_column='status', limit_choices_to={'type': '4'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ghzt', to='htgl.sys', verbose_name='状态')),
            ],
            options={
                'verbose_name': '借用记录',
                'verbose_name_plural': '借用记录',
                'db_table': 'record_device',
                'managed': True,
                'unique_together': {('did', 'borrowid')},
            },
        ),
    ]
