# Generated by Django 3.0.5 on 2020-05-09 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartridge',
            options={'managed': False, 'verbose_name': '硒鼓管理', 'verbose_name_plural': '硒鼓管理'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'managed': False, 'verbose_name': '设备管理', 'verbose_name_plural': '设备管理'},
        ),
        migrations.AlterModelOptions(
            name='printer',
            options={'managed': False, 'verbose_name': '打印机管理', 'verbose_name_plural': '打印机管理'},
        ),
        migrations.AlterModelOptions(
            name='recordapply',
            options={'managed': False, 'verbose_name': '耗材申领记录', 'verbose_name_plural': '耗材申领记录'},
        ),
        migrations.AlterModelOptions(
            name='recordaudit',
            options={'managed': False, 'verbose_name': '借用审批记录', 'verbose_name_plural': '借用审批记录'},
        ),
        migrations.AlterModelOptions(
            name='recordborrow',
            options={'managed': True, 'verbose_name': '设备借用申请', 'verbose_name_plural': '设备借用申请'},
        ),
    ]
