# Generated by Django 3.0.5 on 2020-05-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0002_borrowdetail_cartridge_department_device_member_printer_printertype_recordapply_recordaudit_recordbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ecsstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='名称')),
            ],
            options={
                'verbose_name': '状态',
                'verbose_name_plural': '状态',
                'db_table': 'ecsstatus',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='内网IP')),
                ('internetip', models.CharField(blank=True, max_length=15, null=True, verbose_name='互联网ip')),
                ('os', models.CharField(max_length=30, verbose_name='操作系统')),
                ('sn', models.CharField(editable=False, max_length=50, unique=True, verbose_name='实例id')),
                ('net', models.CharField(choices=[('VPN1', 'VPN1'), ('VPN2', 'VPN2'), ('VPN3', 'VPN3')], max_length=4)),
                ('group', models.IntegerField(choices=[('1', '转塘集群'), ('2', '青山湖集群')])),
                ('cpu', models.CharField(blank=True, max_length=20, null=True, verbose_name='CPU')),
                ('ram', models.CharField(blank=True, max_length=20, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, max_length=20, null=True, verbose_name='硬盘')),
                ('memo', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('recordtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.PROTECT, to='htgl.ecsstatus', verbose_name='状态')),
            ],
            options={
                'verbose_name': '云服务器',
                'verbose_name_plural': '云服务器',
                'db_table': 'ecs',
                'managed': True,
            },
        ),
    ]
