# Generated by Django 3.0.5 on 2020-05-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0002_borrowdetail_cartridge_department_device_member_printer_recordapply_recordaudit_recordborrow_recordd'),
    ]

    operations = [
    ]
