# Generated by Django 3.0.5 on 2020-05-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0002_auto_20200520_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dingid',
            field=models.CharField(blank=True, db_column='dingID', max_length=20, null=True, unique=True, verbose_name='dingID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='dingid',
            field=models.CharField(blank=True, db_column='dingID', max_length=20, null=True, unique=True, verbose_name='钉钉编号'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='depid',
            field=models.ForeignKey(db_column='depID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.department', to_field='dingid', verbose_name='申请处室'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='userid',
            field=models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.member', to_field='dingid', verbose_name='申请人'),
        ),
    ]
