# Generated by Django 3.0.5 on 2020-05-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0002_auto_20200509_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordborrow',
            name='etime',
            field=models.DateField(blank=True, null=True, verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='stime',
            field=models.DateField(blank=True, null=True, verbose_name='借用时间'),
        ),
    ]
