# Generated by Django 3.0.5 on 2020-05-16 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0003_ecs_ecsstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecs',
            name='sort',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='cpu',
            field=models.CharField(blank=True, default='8核', max_length=20, null=True, verbose_name='CPU'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='disk',
            field=models.CharField(blank=True, default='500G', max_length=20, null=True, verbose_name='硬盘'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='group',
            field=models.IntegerField(choices=[(1, '转塘集群'), (2, '青山湖集群')], default=1),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='net',
            field=models.CharField(choices=[('VPN1', 'VPN1'), ('VPN2', 'VPN2'), ('VPN3', 'VPN3')], default='VPN1', max_length=4),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='ram',
            field=models.CharField(blank=True, default='16G', max_length=20, null=True, verbose_name='内存'),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='status',
            field=models.ForeignKey(db_column='status', default=1, on_delete=django.db.models.deletion.PROTECT, to='htgl.ecsstatus', verbose_name='状态'),
        ),
    ]
