# Generated by Django 3.0.5 on 2020-05-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0004_auto_20200510_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='codetype',
        ),
        migrations.AlterField(
            model_name='department',
            name='depname',
            field=models.CharField(blank=True, db_column='depName', max_length=20, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='房间号'),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[(1, '个人使用'), (2, '处室使用')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sys',
            name='codename',
            field=models.CharField(blank=True, db_column='codeName', max_length=20, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='sys',
            name='type',
            field=models.IntegerField(blank=True, choices=[('1', '设备类别'), ('2', '设备状态')], null=True, verbose_name='代码类别'),
        ),
    ]
