# Generated by Django 3.0.5 on 2020-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0005_auto_20200511_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'managed': True, 'verbose_name': '部门管理', 'verbose_name_plural': '部门'},
        ),
        migrations.AlterField(
            model_name='sys',
            name='type',
            field=models.IntegerField(blank=True, choices=[('2', '设备状态'), ('1', '设备类别')], null=True, verbose_name='代码类别'),
        ),
    ]
