# Generated by Django 3.0.5 on 2020-05-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0005_auto_20200516_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecs',
            name='os',
            field=models.CharField(default='Windows Server 2008 R2 企业版 64位中文版', max_length=50, verbose_name='操作系统'),
        ),
    ]
