# Generated by Django 3.0.5 on 2020-05-18 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0006_auto_20200516_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowDetail',
        ),
        migrations.DeleteModel(
            name='RecordAudit',
        ),
        migrations.AlterModelOptions(
            name='recordborrow',
            options={'managed': True, 'verbose_name': '设备借用', 'verbose_name_plural': '设备借用'},
        ),
        migrations.AlterModelOptions(
            name='recorddevice',
            options={'managed': True, 'verbose_name': '设备借用记录', 'verbose_name_plural': '设备借用记录'},
        ),
        migrations.RemoveField(
            model_name='recordborrow',
            name='department',
        ),
        migrations.RemoveField(
            model_name='recordborrow',
            name='deptid',
        ),
        migrations.RemoveField(
            model_name='recordborrow',
            name='username',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='ctime',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='department',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='deptid',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='etime',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='return_field',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='rtime',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='stime',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='type',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='recorddevice',
            name='username',
        ),
        migrations.AddField(
            model_name='device',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dingID',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='钉钉编号'),
        ),
        migrations.AddField(
            model_name='recordborrow',
            name='depid',
            field=models.ForeignKey(db_column='depID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.department', verbose_name='责任处室'),
        ),
        migrations.AddField(
            model_name='recordborrow',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='recorddevice',
            name='borrowid',
            field=models.ForeignKey(db_column='borrowID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.RecordBorrow', verbose_name='借用id'),
        ),
        migrations.AddField(
            model_name='recorddevice',
            name='returntime',
            field=models.DateField(blank=True, null=True, verbose_name='归还时间'),
        ),
        migrations.AddField(
            model_name='recorddevice',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', limit_choices_to={'type': '4'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ghzt', to='htgl.sys', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='recorddevice',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='ecs',
            name='os',
            field=models.CharField(default='Windows Server 2008 R2', max_length=50, verbose_name='操作系统'),
        ),
        migrations.RemoveField(
            model_name='recordborrow',
            name='devices',
        ),
        migrations.AddField(
            model_name='recordborrow',
            name='devices',
            field=models.ManyToManyField(to='htgl.Device', verbose_name='设备列表'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='recordtime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='生成时间'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', limit_choices_to={'type': '3'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyzt', to='htgl.sys', verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='userid',
            field=models.ForeignKey(db_column='userid', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.member'),
        ),
        migrations.AlterField(
            model_name='recorddevice',
            name='did',
            field=models.ForeignKey(db_column='dID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.Device', verbose_name='设备id'),
        ),
        migrations.AlterField(
            model_name='recorddevice',
            name='recordtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sys',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, '设备类别'), (2, '设备状态'), (3, '设备审批'), (4, '借用状态')], null=True, verbose_name='代码类别'),
        ),
    ]
