# Generated by Django 3.0.5 on 2020-05-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0006_auto_20200520_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='xuqiu',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='描述'),
        ),
    ]
