# Generated by Django 3.0.5 on 2020-05-11 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0007_auto_20200511_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(blank=True, choices=[(1, '个人使用'), (2, '处室使用')], max_length=1, null=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.ForeignKey(db_column='type', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.sys', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='sys',
            name='type',
            field=models.IntegerField(blank=True, choices=[('1', '设备类别'), ('2', '设备状态')], null=True, verbose_name='代码类别'),
        ),
    ]
