# Generated by Django 3.0.5 on 2020-05-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0008_auto_20200511_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printer',
            options={'managed': True, 'verbose_name': '打印机型号', 'verbose_name_plural': '型号'},
        ),
        migrations.CreateModel(
            name='PrinterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=50, null=True, verbose_name='型号')),
                ('brand', models.CharField(blank=True, max_length=10, null=True, verbose_name='品牌')),
                ('pic', models.CharField(blank=True, max_length=100, null=True)),
                ('cartridges', models.ManyToManyField(to='htgl.Cartridge', verbose_name='使用的硒鼓')),
            ],
            options={
                'verbose_name': '打印机型号',
                'verbose_name_plural': '型号',
                'db_table': 'printertype',
                'managed': True,
            },
        ),
    ]
