# Generated by Django 3.0.5 on 2020-05-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0008_auto_20200520_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xuqiu',
            name='feedbacktime',
            field=models.DateField(blank=True, null=True, verbose_name='反馈时间'),
        ),
        migrations.AlterField(
            model_name='xuqiu',
            name='manager',
            field=models.ForeignKey(blank=True, db_column='manager', limit_choices_to={'type': '5'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r3', to='htgl.sys', verbose_name='负责人'),
        ),
        migrations.AlterField(
            model_name='xuqiu',
            name='plantime',
            field=models.DateField(blank=True, null=True, verbose_name='计划完成时间'),
        ),
        migrations.AlterField(
            model_name='xuqiu',
            name='zt',
            field=models.ForeignKey(blank=True, db_column='zt', limit_choices_to={'type': '6'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='r1', to='htgl.sys', verbose_name='状态'),
        ),
    ]
