# Generated by Django 3.0.5 on 2020-06-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0009_auto_20200520_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordborrow',
            name='reason',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='借用原因'),
        ),
    ]
