# Generated by Django 3.0.5 on 2020-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0012_auto_20200713_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='department',
            field=models.CharField(max_length=10, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='name',
            field=models.CharField(max_length=10, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='userid',
            field=models.CharField(max_length=15, null=True, verbose_name='用户id'),
        ),
    ]
