# Generated by Django 3.0.5 on 2020-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0013_auto_20200714_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='姓名'),
        ),
    ]
