# Generated by Django 3.0.5 on 2020-07-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0014_auto_20200714_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='department',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='userid',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='用户id'),
        ),
    ]
