# Generated by Django 3.0.5 on 2020-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0015_auto_20200714_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='pic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='图片'),
        ),
    ]
