# Generated by Django 3.0.5 on 2020-07-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0016_advice_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='pic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='图片'),
        ),
    ]
