# Generated by Django 3.0.5 on 2020-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0017_auto_20200715_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='userid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户id'),
        ),
    ]
