# Generated by Django 3.0.5 on 2020-07-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0018_auto_20200715_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='department',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='advice',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名'),
        ),
    ]
