# Generated by Django 3.0.5 on 2020-07-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0019_auto_20200715_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='depid',
            field=models.ForeignKey(blank=True, db_column='depID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.department', verbose_name='责任处室'),
        ),
        migrations.AlterField(
            model_name='device',
            name='memid',
            field=models.ForeignKey(blank=True, db_column='memID', null=True, on_delete=django.db.models.deletion.PROTECT, to='htgl.member', verbose_name='责任人'),
        ),
    ]
