# Generated by Django 3.0.5 on 2020-08-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0020_auto_20200729_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordborrow',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='htgl.Device', verbose_name='借用设备'),
        ),
    ]
