# Generated by Django 3.0.5 on 2020-08-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0021_auto_20200810_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='title',
            field=models.CharField(default='测试意见', max_length=20, verbose_name='标题'),
            preserve_default=False,
        ),
    ]
