# Generated by Django 3.0.5 on 2020-09-16 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0022_advice_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(max_length=1000, verbose_name='内容')),
                ('recordtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('sort', models.IntegerField(default=99, verbose_name='排序')),
            ],
            options={
                'verbose_name': '大事记',
                'verbose_name_plural': '大事记',
                'db_table': 'diary',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='devices',
            field=models.ManyToManyField(to='htgl.Device', verbose_name='借用设备'),
        ),
        migrations.AlterField(
            model_name='recordborrow',
            name='status',
            field=models.ForeignKey(blank=True, db_column='status', default=15, limit_choices_to={'type': '3'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jyzt', to='htgl.sys', verbose_name='状态'),
        ),
    ]
