# Generated by Django 3.0.5 on 2020-11-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0023_auto_20200916_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='项目名称')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='项目编号')),
                ('budget', models.CharField(blank=True, max_length=20, null=True, verbose_name='预算')),
                ('dep1', models.CharField(blank=True, max_length=20, null=True, verbose_name='负责部门')),
                ('dep2', models.CharField(blank=True, max_length=50, null=True, verbose_name='承建方')),
                ('contact1', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目负责人')),
                ('contact2', models.CharField(blank=True, max_length=50, null=True, verbose_name='承建方负责人')),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True, verbose_name='监理')),
                ('time1', models.CharField(blank=True, max_length=20, null=True, verbose_name='申报时间')),
                ('time2', models.CharField(blank=True, max_length=20, null=True, verbose_name='建设时间')),
                ('time3', models.CharField(blank=True, max_length=20, null=True, verbose_name='验收时间')),
                ('file1', models.FileField(blank=True, null=True, upload_to='./upload', verbose_name='建设方案')),
                ('memo', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
                'db_table': 'project',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='cartridge',
            options={'managed': True, 'verbose_name': '耗材', 'verbose_name_plural': '耗材'},
        ),
    ]
