# Generated by Django 3.0.5 on 2020-11-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0024_auto_20201120_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='~/upload', verbose_name='建设方案'),
        ),
    ]
