# Generated by Django 3.0.5 on 2020-11-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0025_auto_20201120_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='建设方案'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time1',
            field=models.DateField(blank=True, null=True, verbose_name='申报时间'),
        ),
    ]
