# Generated by Django 3.0.5 on 2020-11-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htgl', '0026_auto_20201121_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time2',
            field=models.DateField(blank=True, null=True, verbose_name='建设时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time3',
            field=models.DateField(blank=True, null=True, verbose_name='验收时间'),
        ),
    ]
